ci: integration with TiCS code quality analysis
canonical/chisel pull request #138
Opened 2024-06-12 12:50 UTC by cjdcordeiro

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

This PR introduces the TiCS analyzer with the Chisel CI. 

## How it works

### On every PR

TiCS job will run in "client" mode, analyzing the changed files in the PR. As a result, it will create code annotations and write a comment to the PR with a summary of the analysis. Example: https://github.com/cjdcordeiro/chisel/pull/3#issuecomment-2162543160

### On-demand and on-schedule

At least once a day, this job will also run in "qserver" mode, meaning that it will do a full analysis of the Chisel project and send the results to our remote dashboard in Tiobe. Here's an example of such run: https://github.com/cjdcordeiro/chisel/actions/runs/9480198560 (and the corresponding [view](https://canonical.tiobe.com/tiobeweb/TICS/TqiDashboard.html#axes=Project(chisel)) in the dashboard)

2024-06-12 12:55 UTC, cjdcordeiro commented
@letFunny are the annotations in https://github.com/cjdcordeiro/chisel/actions/runs/9480198560 legit? The coverage issue we saw a few days ago has been fixed (the tool requires a pre-existing coverage report).

2025-01-20 10:17 UTC, letFunny reviewed
Looks good to me, just a couple of questions.

2025-01-20 10:17 UTC, letFunny commented on .github/workflows/tics.yml
> +          repository: ${{ needs.set-project.outputs.repo }}
Why can't the previous job be inlined here?

2025-01-20 10:17 UTC, letFunny commented on .github/workflows/tics.yml
> +          filelist: ${{ env.TICS_FILELIST }}
We need to exclude `testutil` and the new `apachetestutil` maybe we should do it here directly.

2025-02-20 09:53 UTC, cjdcordeiro commented on .github/workflows/tics.yml
> +          repository: ${{ needs.set-project.outputs.repo }}
technically it could, but there are a few reasons that led me to split it this way:
 - segregation of concerns: the 1st one is a preparatory step, while the 2nd one is the analysis
 - permissions: the 2nd one has additional permissions ("write to PRs") that the 1st one doesn't need

If there's a strong reason to merge the two, I'm not opposed to doing it.

2025-02-20 10:01 UTC, niemeyer requested changes
In the example I see a green checkmark with zero details about what it means to pass/not-pass, let alone the gradient that was accounted for.  That's some very prominent space, with no clear benefits.

I may be missing something, but in principle if we are to integrate something like this, it should have better statistics, and ideally be integrated into the workflow like every other test runner we have.

2025-02-20 11:11 UTC, cjdcordeiro commented on .github/workflows/tics.yml
> +          filelist: ${{ env.TICS_FILELIST }}
Noted. As per our discussion, `testutil` is indeed just used within the project's tests. And even though TiCS knows what's PRODUCTION vs TEST code, it will take those utilities as PRODUCTION code.

This PR is getting blocked for the time being, but I'll keep this thread open for future reference

2025-02-20 11:32 UTC, cjdcordeiro commented
> [!IMPORTANT]  
> This PR was discussed offline, and as per the [above comment](https://github.com/canonical/chisel/pull/138#pullrequestreview-2629333576) we've agreed that the feedback provided by this new CI action adds unnecessary noise to the PRs and is not very handy or relevant for assessing the PRs' quality. 
> 
> We're then **Closing** this PR and escalating the need for better integration of the results with the PRs, otherwise we're just ticking a box for the sake of having a check that most reviewers won't care to look at.

2025-02-20 11:32 UTC, closed without merging