chose: expose manifest reading and jsonwall as packages
canonical/chisel pull request #182
Opened 2024-12-13 12:15 UTC by letFunny

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

2024-12-19 15:35 UTC, cjdcordeiro requested changes
We'll likely need to add the new [licensing headers](https://spdx.dev/learn/overview/#identifiers) to each one of these source files

2025-01-07 10:56 UTC, cjdcordeiro reviewed
thanks for adding the licensing headers. they lgtm

2025-01-07 10:58 UTC, cjdcordeiro commented
> [!NOTE]
> pls ignore the failed RTD check. I've enabled the automatic generation of PR docs, which will start passing once #185 is merged

2025-01-08 07:31 UTC, cjdcordeiro requested changes

2025-01-08 07:31 UTC, cjdcordeiro commented on pkg/manifest/manifest.go
> +	"github.com/canonical/chisel/internal/setup"
Given that chisel/internal is under AGPL, is this ok?

2025-01-08 07:31 UTC, cjdcordeiro commented on pkg/manifest/manifest_test.go
> +	"github.com/canonical/chisel/internal/testutil"
Same comment here as above

2025-01-08 09:00 UTC, letFunny commented on pkg/manifest/manifest.go
> +	"github.com/canonical/chisel/internal/setup"
Honestly, I am not sure. I have to read more about licensing, but it looks like it will not be okay, we would have to extract the common components into a Apache-2.0 package that is imported by both the AGPL and this one, but I am not really sure.

2025-01-08 10:10 UTC, letFunny commented
I am blocking this until we solve all the questions regarding copyright and licensing.

2025-01-16 12:47 UTC, letFunny commented on pkg/manifest/manifest.go
> +	"github.com/canonical/chisel/internal/setup"
Solved in the last version.

2025-01-16 12:48 UTC, letFunny commented on pkg/manifest/manifest_test.go
> +	"github.com/canonical/chisel/internal/testutil"
AGPL imports in the tests are more dubious, but I have also changed it so we do not depend on that. I have also added a script for the CI to check that we never import AGPL code into the external ones.

2025-01-16 14:55 UTC, cjdcordeiro approved these changes
Thanks for taking care of the licenses and adding the CI ;) it lgtm from a structural point of view

2025-01-24 17:17 UTC, niemeyer requested changes
Thank you.  Probably final details:

2025-01-24 17:17 UTC, niemeyer commented on internal/manifestutil/manifestutil.go
> +	"github.com/canonical/chisel/pkg/manifest"
As we discussed, historically the `pkg/` directory has contained cached binary content produced by the _go_ tool, so while I know there are suggestions in some non-official third-party standards that recommend the use of `pkg/` like this, this is indeed non-standard/non-official and not widely followed, and should probably not be widely followed due to the conflict with longstanding practices.

For our purposes, I suggest naming this directory as `public/`, as a nice counterpart to `internal/`, and a good reminder to those using and changing its content that a different mindset must be applied to the content there.

2025-01-27 11:16 UTC, letFunny commented on cmd/chisel/cmd_info.go
> +	sliceExists := func(key apacheutil.SliceKey) bool {
This is a very good idea, I didn't know this could be used in Go, amazing.

2025-01-27 11:46 UTC, letFunny commented on internal/manifestutil/manifestutil.go
> +	"github.com/canonical/chisel/pkg/manifest"
Done, thanks for the suggestion.

2025-01-27 12:00 UTC, letFunny commented on pkg/manifest/manifest.go
> +func Validate(manifest *Manifest) (err error) {
We discussed the exports in the meeting but probably we went over them too fast. This is the pastebin: https://pastebin.canonical.com/p/cDwhTmqpvr/.

In the case of the `Validate` is was thinking about it in terms of compatibility with the linked current version of the library and to also check for internal consistency. I am not sure I understand what you are saying, but given that we also include the manifest type and fields, isn't there a reasonable expectation that if we change the format old versions of Chisel won't be able to read it anyway?

2025-01-27 14:20 UTC, niemeyer commented on pkg/manifest/manifest.go
> +func Validate(manifest *Manifest) (err error) {
Remember the many issues we had to overcome recently about changing `chisel.yaml` and the consequences for past and future revisions?  Now imagine such issues on a file that is actually impossible to update, because there are baked images out there carrying the old format for good. Not only that, but we also have _code_ out there, that we cannot update ourselves, that manipulate such files.

>isn't there a reasonable expectation that if we change the format old versions of Chisel won't be able to read it anyway?

Have you reviewed the existing code with the mindset that it must not trust on details that could break future tweaking of the file?  It's quite possible that it's totally okay, but I haven't at least.  Let me draw a trivial analogy: imagine a JSON parser - depending on how you build it, it's possible you can break the parser without breaking the format.  One is a specification, the other is an algorithm. Does that make more sense?

2025-01-27 14:23 UTC, letFunny commented on pkg/manifest/manifest.go
> +func Validate(manifest *Manifest) (err error) {
> One is a specification, the other is an algorithm

That made the point clear, I get it now.

2025-01-27 16:02 UTC, niemeyer requested changes

2025-01-27 16:02 UTC, niemeyer commented on internal/setup/setup.go
> +	Essential []SetupKey
What is a "setup key"?  This used to be the key for a package slice, thus SliceKey.

2025-01-27 16:19 UTC, letFunny commented on internal/setup/setup.go
> +	Essential []SetupKey
I thought you had decided that it was a better name when you used it in your previous comment :). I see now that it was a typo.

2025-01-27 16:30 UTC, niemeyer commented on internal/setup/setup.go
> +	Essential []SetupKey
Ah, sorry about that.

2025-01-27 16:36 UTC, niemeyer approved these changes
Thanks for all the changes.

2025-01-27 16:37 UTC, merged