Set umask in tests to 0002
canonical/chisel pull request #32
Opened 2022-10-02 11:51 UTC by woky

deb/extract and fsutil/create tests expect umask 0002. This depends on
environment so set it explicitly in tests.

2022-10-03 06:24 UTC, cjdcordeiro commented
how did you encounter the issue? (I'm trying to reproduce the problem without umask)

2022-10-03 10:18 UTC, woky commented
> how did you encounter the issue? (I'm trying to reproduce the problem without umask)

One day I tried to run chisel tests on my workstation at home which runs ArchLinux, which has default umask of 022. Ubuntu has 002.

2022-10-03 12:18 UTC, cjdcordeiro approved these changes

2022-10-03 12:58 UTC, niemeyer requested changes
Again, per review in the other PR, it should not depend on umask. The permissions that come in the package should be respected as-is.

2022-10-03 13:04 UTC, woky commented
> Again, per review in the other PR, it should not depend on umask. The permissions that come in the package should be respected as-is.

The problem is with the test. It creates file with wrong permissions when umask from the environment is not set to 022. I think it's in `archive_test.go` but I can't test it now, because it fails on
```
$ go test ./internal/archive/
# github.com/canonical/chisel/internal/archive_test [github.com/canonical/chisel/internal/archive.test]
internal/archive/archive_test.go:48:22: undefined: archive.FakeDo
FAIL	github.com/canonical/chisel/internal/archive [build failed]
FAIL
```

2022-10-03 13:57 UTC, niemeyer commented
> The problem is with the test.

So let's fix the test. The point I've been trying to make is that we don't want to change the environment of the actual code being tested to fix tests, as otherwise we might be hiding a real bug that needs to be fixed. We should instead create the tested files with the actual correct permissions. There's logic already there to do that inside the implementation, for instance.

2022-10-05 10:50 UTC, woky commented
@niemeyer You are right. I'm going to close this one and open another one.

2022-10-05 10:50 UTC, closed without merging